
USE scraping;

DROP TABLE IF EXISTS GEOMETRY_MUNICIPIOS;

create table if not exists GEOMETRY_MUNICIPIOS(
COD_INE              TEXT,
ID_REL               TEXT,
COD_GEO              TEXT,
COD_PROV             TEXT,
PROVINCIA            TEXT,
NOMBRE_ACTUAL        TEXT,
POBLACION_MUNI       TEXT,
SUPERFICIE           TEXT,
PERIMETRO            TEXT,
COD_INE_CAPITAL      TEXT,
CAPITAL              TEXT,
POBLACION_CAPITAL    TEXT,
HOJA_MTN25_ETRS89    TEXT,
LONGITUD_ETRS89      TEXT,
LATITUD_ETRS89       TEXT,
ORIGENCOOR           TEXT,
ALTITUD              TEXT,
ORIGENALTITUD        TEXT);

LOAD DATA LOCAL INFILE 'data/municipios_geo_data_nomenclator.csv'
INTO TABLE GEOMETRY_MUNICIPIOS
CHARACTER SET 'utf8'
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n';

